[package]
name = "kontroli"
version = "0.3.0"
authors = ["Michael Färber <michael.faerber@gedenkt.at>"]
edition = "2021"
description = "Type checking for the lambda-Pi calculus modulo rewriting"
readme = "../README.md"
repository = "https://github.com/01mf02/kontroli-rs"
license = "GPL-3.0-only"
keywords = ["verification", "dependent-types", "type-checking", "rewriting", "dedukti"]
categories = ["concurrency", "no-std", "science"]

[dependencies]
dedukti-parse = { version = "0.2", path = "../dedukti-parse" }
fnv = "1.0.7"
im = "15.1.0"
lazy-st = "0.2"
log = "0.4.17"
nested-modules = "0.2"

[lib]
bench = false

[dev-dependencies]
colosseum = "0.2"
criterion = "0.3.5"

[[bench]]
name = "bench"
harness = false
